### ISSUE TITLE
Request a package update

### ISSUE THREAD

**Issue by Orden4** [Drake53/CSharp.lua#7]
Am not entirely sure what the state is of the CSharpLua 2.0 pre-release packages compared to v1.7.x/v1.8.0-preview.1, but I recently got a particularly notable PR merged into CSharpLua: https://github.com/yanghuan/CSharp.lua/pull/435
I've basically been working on an alternative API to War3Api that uses property templates to allow for a lot of cool and convenient stuff -> https://github.com/Orden4/WCSharp/tree/dev-api/WCSharp.Api
I can release a first version of it in the very near future, but an updated CSharpLua package is obviously required for this.

I know you've mentioned not to expect package updates in the near future elsewhere, but this isn't really like the usual random bugfix, so I'd like to request that an exception be made.

Also, while I'm at this, it's worth requesting your thoughts on the option of alternatively including this into War3Api natively one last time. I did bring this up before, but that was like a year ago, and I didn't do much with the project for a long time in between as I was focused on creating Spectrum TD instead.

Anyway, the intent of WCSharp.Api is as follows:
- (Done) Identically to War3Api, provide all of the base functionality in the various `.j` scripts
- (Done) Add properties/methods for all of the various BlzGet/SetField stuff that has some documentation built in (see ability.cs)
- (WIP, but can be added gradually) Expose convenient properties and methods on objects such as units (e.g. `unit.Life += 50;`, `unit.Kill();`, etc.).
- (To do) Integrate with [jassdoc](https://github.com/lep/jassdoc) to provide IntelliSense documentation where available.

With the additional requirement that all of this is done via CSharpLua compile templates, so the API will not add any overhead or file size.
Initially I also planned to design the API as something that has compatibility with War3Api, but after some further consideration (as well as some small chats with other C# mapmakers), I felt that it was more straight forward to just look to have it act as a replacement to War3Api. This is actually quite doable, as to my knowledge there still aren't really any packages besides WCSharp, so if I upgrade them and use the same class names, I can allow for seamless transitioning from War3Api to WCSharp.Api, and can hopefully just take over as the new standard.
So, while this replacing is certainly possible, I do still think that it would be ideal if we can avoid creating two competing standards.

**Comment by Drake53** [comment]
Regarding the package update, since it's only the CSharpLua packages and not War3Net I have no issue doing that right now, I just need to generate a new nuget API key since my current one expired, but the new version should be up later today.

Regarding the alternative api, I made War3Api as an easy solution to get started with C# in wc3 by simply autogenerating the entire thing from the .j files. It was the intention to someday replace it with a more object-oriented API since obviously putting thousands of static methods in a single class is not a good experience, I just never got around to it and I don't think I ever will, especially if someone else is working on such a thing already. So yeah I'd say a replacement is very much welcomed. Though I think War3Api will still have its use in transpiling code from jass/vjass to C#.

**Comment by Orden4** [comment]
Fair enough! Thanks in advance.
